### ISSUE TITLE
Help me 😊

### ISSUE THREAD

**Issue by funmolde** [12pecur/Recaptcha-Bot#1]
Hi 
how did you install webbrowser? pip install webbrowser doesn't work 

ERROR: Could not find a version matching webbrowser requirement (from versions: none)
ERROR: No matching distribution was found for webbrowser

How does the script work? 
Thank You

**Comment by 12pecur** [comment]
Hi
sorry for the mistake I have changed it now! webbrowser is already a pre-installed library in Python 3 or above, therefore you may not even need to install it, I just included it for those who run any version of Python. Once again, I apologize for the inconvenience.

The script works by imitating human movement such as curves in mouse movement and diffreant paced lines a swell as direction. This is one of the backends of recaptcha that is being tackled, which is human movement. You may not realise, but REcaptacha tracks EVERYTHING. From mouse movement (I bypassed this in my code :) ) to cookies, and recent search history. This prevents bots from solving it. As you may know there are already bots that can solve REcaptcha puzzles however, they are not able to imitate the mouse movement of a human or the history and cookies generated by a human. 

For any additional questions or inquiries please feel free to ask! **A follow would be much appreciated :)** 
Thank you for commenting on my project, as it means a lot to me.

**Comment by funmolde** [comment]
Thanks You 😀, I can run the script.
It works but not all the time like in the video.
does not work at all on https://www.google.com/recaptcha/api2/demo

https://github.com/12pecur/Recaptcha-Bot/assets/13144261/3da56a1d-f3a3-48ed-ad92-502f52c4594c
Thank You -_-

**Comment by 12pecur** [comment]
Hi Again,
Sorry for the inconvenience once again. If you mean that the bot does not hit the checkbox, I may adjust the code just for you.  If you could please send me the resolution of your monitor. I would be able to tailor the experience to you! 

Thanks again! 😁

**Comment by 12pecur** [comment]
For any further inquiries or assets that you want tailored to you or even extra actions, please tell me them, as I would be happy to help you. 

It is a pleasure that I was able to help you.
